name: prettier
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          args: --list-different "**/*.md"
