name: ruby
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jidicula/clang-format-action@v4.8.0
        with:
          clang-format-version: "14"
          check-path: ruby

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential ruby-dev bundler
      - name: Build extension
        run: |
          pushd ./ruby/command-t/ext/command-t
          ruby extconf.rb --vendor
          make
          popd
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec -Iruby
